export const environment = {
  production: false,
  t2y12PruGU9wUtEGzBJfolMIgK: 'CHANGEIT',
  VERSION: require('../../package.json').version,
  remoteConfig: false,
  remoteConfigUrl: './design-studio-config.json',
  apiUrl: 'http://localhost:3001/',
  widgetBaseUrl: 'http://localhost:8090/widget',
  dashboardBaseUrl: 'http://localhost:8090/',
  wsUrl: 'ws://localhost:3001/',
  whatsappTemplatesBaseUrl: 'http://localhost:3000/',
  uploadEngine: 'native',
  baseImageUrl: 'CHANGEIT',
  logLevel: 'error',
  aiModels: 'CHANGEIT',
  storage_prefix: 'cds_sv6',
  firebaseConfig: {
    apiKey: 'CHANGEIT',
    authDomain: 'CHANGEIT',
    databaseURL: 'CHANGEIT',
    projectId: 'CHANGEIT',
    storageBucket: 'CHANGEIT',
    messagingSenderId: 'CHANGEIT',
    appId: 'CHANGEIT',
    vapidKey: 'CHANGEIT',
  },
};
